<?php
session_start();
$apiKey = 'rzp_test_3o4fXyDTQEHKwu';
?>


<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="icon" href="../dist/images/fox-svgrepo-com.svg">
</head>
<body>
    
</body>
</html>

<div class="flex-dir-col text-center content-center align-middle justify-center">
<h1 class="mb-4 justify-items-center p-20 bg-gray-100 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xs">Payment Portal</h1>

<form action="success.php" method="POST" class="mr-96 ml-96 mt-20 text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mb-2">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="100" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Property Rental"
    data-description="Training & Development!"
    data-image="https://traidev.com/img/web-desgin-development.png"
    data-prefill.name="<?php echo $_SESSION['bookingname'];?>"
    data-prefill.email="<?php echo $_SESSION['bookingemail'];?>"
    data-prefill.contact="<?php echo $_SESSION['bookingmobile'];?>"
    data-theme.color="#F37254"
></script>
</div>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>
